# This is a TOML document for nethunter device configs.

[[device]]

common_name = "Nexus 5"
product_name = "hammerhead"

nhos_file = "lineage-14.1-20171008-UNOFFICIAL-hammerhead.zip"
nhos_url = "https://build.nethunter.com/installer/nexus5/lineage-14.1-20171008-UNOFFICIAL-hammerhead.zip"

nhfs_file = "update-nethunter-generic-armhf-20171007_215146.zip"
nhfs_url = "https://build.nethunter.com/installer/generic/update-nethunter-generic-armhf-20171007_215146.zip"

gapps_file = "open_gapps-arm-7.1-mini-20171007.zip"
gapps_url = "https://build.nethunter.com/installer/gapps/open_gapps-arm-7.1-mini-20171007.zip"

twrp_file = "twrp-3.1.1-0-hammerhead.img"
twrp_url = "https://dl.twrp.me/hammerhead/twrp-3.1.1-0-hammerhead.img"

[[device]]

common_name = "Nexus 5X fixme"
product_name = "bullhead"

nhos_file = "BULLHEAD_FIXME.zip"
nhos_url = "BULLHEAD_FIXME/misc/nexus5_installer/nethunter_hammerhead-ota-f91313a12f.zip"

nhfs_file = "update-nethunter-generic-armhf-20171007_215146.zip"
nhfs_url = "https://build.nethunter.com/installer/generic/update-nethunter-generic-armhf-20171007_215146.zip"

gapps_file = "open_gapps-arm-7.1-mini-20171007.zip"
gapps_url = "https://build.nethunter.com/installer/gapps/open_gapps-arm-7.1-mini-20171007.zip"

twrp_file = "twrp-3.1.1-0-bullhead.img"
twrp_url = "https://dl.twrp.me/bullhead/twrp-3.1.1-0-bullhead.img"

[[device]]

common_name = "OnePlus 5"
product_name = "OnePlus 5"

nhos_file = "lineage-14.1-20171008-UNOFFICIAL-cheeseburger.zip"
nhos_url = "https://build.nethunter.com/installer/oneplus5/lineage-14.1-20171008-UNOFFICIAL-cheeseburger.zip"

nhfs_file = "update-nethunter-generic-armhf-20171007_215146.zip"
nhfs_url = "https://build.nethunter.com/installer/generic/update-nethunter-generic-armhf-20171007_215146.zip"

gapps_file = "open_gapps-arm-7.1-mini-20171007.zip"
gapps_url = "https://build.nethunter.com/installer/gapps/open_gapps-arm-7.1-mini-20171007.zip"

twrp_file = "twrp-3.1.1-1-cheeseburger.img"
twrp_url = "https://dl.twrp.me/cheeseburger/twrp-3.1.1-1-cheeseburger.img"

extra_file = "oneplus_5_oxygenos_4.5.10_firmware.zip"
extra_url = "https://build.nethunter.com/installer/oneplus5/oneplus_5_oxygenos_4.5.10_firmware.zip"